### ISSUE TITLE
train.py  Use padding[j] = pca_result[int(data[j]-1)] ,why not ppa_result?

### ISSUE THREAD

**Issue by X-zhihao** [Aquariuaa/LightLog#2]
> `def read_data(split = 0.7):

    logs_data = pd.read_csv('./data/bgl_data.csv')
    logs_data = logs_data.values
    label = pd.read_csv('./data/bgl_label.csv')
    label = label.values
    logs = []
    for i in range(0,len(logs_data)):
        padding = np.zeros((300,20))
        data = logs_data[i]
        for j in range(0,len(data)):
            # padding[j] = pca_result[int(data[j]-1)]
            padding[j] = pca_result[int(data[j]-1)]
        padding = list(padding)
        logs.append(padding)
    logs = np.array(logs)`

I see you use pca_result, but why not ppa_result?

**Comment by X-zhihao** [comment]
In Enhanced TCN for Log Anomaly Detection on the BGL Dataset\train.py and test_BGL.py

**Comment by Aquariuaa** [comment]
Sorry for the late reply, this is a function name that was not changed when doing the comparison test, just correct it to ppa, see train.py on HDFS.
